#!/bin/sh
# Invoked by BuildNumberPlugin before every build. Increments a persistent counter
# (stored inside the plugin work directory, under .build/ — never committed) and
# regenerates BuildInfo.swift with the new value.
set -eu

counter_file="$1"
output_file="$2"

prev=0
if [ -f "$counter_file" ]; then
    prev=$(cat "$counter_file")
fi
next=$((prev + 1))
echo "$next" > "$counter_file"

cat > "$output_file" <<EOF
// Auto-generated by BuildNumberPlugin on every build. Do not edit or commit.
public let elapBuildNumber = "$next"
EOF
